name: benchmarks

on: [pull_request]

permissions:
  contents: read

jobs:
  size:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 50
    - uses: actions/setup-node@v6
      with:
        node-version: '20.x'
    - name: 'Setup temporary files'
      run: |
        echo "BASE_JSON=$(mktemp)" >> $GITHUB_ENV
        echo "PATCH_JSON=$(mktemp)" >> $GITHUB_ENV
    - name: 'Benchmark base'
      run: |
        git checkout -f ${{ github.event.pull_request.base.sha }}
        npm install --loglevel error
        if npm run size -w benchmarks -- -o ${{ env.BASE_JSON }}; then
          echo "Ran successfully on base branch"
        else
          echo "{}" > ${{ env.BASE_JSON }}  # Empty JSON as default
          echo "Benchmark script not found on base branch, using default values"
        fi
    - name: 'Benchmark patch'
      run: |
        git checkout -f ${{ github.event.pull_request.head.sha }}
        npm install --loglevel error
        npm run size -w benchmarks -- -o ${{ env.PATCH_JSON }}
        echo "Ran successfully on patch branch"
    - name: 'Collect results'
      run: |
        mkdir -p benchmark-output
        echo "${{ github.event.pull_request.number }}" > benchmark-output/pr-number.txt
        node packages/benchmarks/compare.js ${{ env.BASE_JSON }} ${{ env.PATCH_JSON }} > benchmark-output/table.md
    - name: 'Upload results'
      uses: actions/upload-artifact@v4
      with:
        name: benchmarks-size
        path: benchmark-output/
        retention-days: 1

  perf:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 50
    - uses: actions/setup-node@v6
      with:
        node-version: '20.x'
    - name: 'Setup temporary files'
      run: |
        echo "BASE_JSON=$(mktemp)" >> $GITHUB_ENV
        echo "PATCH_JSON=$(mktemp)" >> $GITHUB_ENV
    - name: 'Benchmark base'
      run: |
        git checkout -f ${{ github.event.pull_request.base.sha }}
        npm install --loglevel error
        if npm run perf -w benchmarks -- -o ${{ env.BASE_JSON }}; then
          echo "Ran successfully on base branch"
        else
          echo "{}" > ${{ env.BASE_JSON }}  # Empty JSON as default
          echo "Benchmark script not found on base branch, using default values"
        fi
    - name: 'Benchmark patch'
      run: |
        git checkout -f ${{ github.event.pull_request.head.sha }}
        npm install --loglevel error
        npm run perf -w benchmarks -- -o ${{ env.PATCH_JSON }}
        echo "Ran successfully on patch branch"
    - name: 'Collect results'
      run: |
        mkdir -p benchmark-output
        echo "${{ github.event.pull_request.number }}" > benchmark-output/pr-number.txt
        node packages/benchmarks/compare.js ${{ env.BASE_JSON }} ${{ env.PATCH_JSON }} > benchmark-output/table.md
    - name: 'Upload results'
      uses: actions/upload-artifact@v4
      with:
        name: benchmarks-perf
        path: benchmark-output/
        retention-days: 1
